# Generated by Django 5.1.2 on 2024-10-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0019_alter_productimage_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='fullDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
