# Generated by Django 5.1.2 on 2024-11-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0020_alter_product_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="reviews_count",
            field=models.IntegerField(default=0),
        ),
    ]
