# Generated by Django 5.1.2 on 2024-11-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0021_product_reviews_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="product",
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(related_name="products", to="product_app.tag"),
        ),
    ]
