# Generated by Django 5.1.2 on 2024-11-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0022_remove_tag_product_product_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="product",
        ),
        migrations.AddField(
            model_name="product",
            name="images",
            field=models.ManyToManyField(to="product_app.productimage"),
        ),
    ]
