# Generated by Django 5.1.2 on 2024-11-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0025_alter_categoryimage_alt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=5, max_digits=2),
        ),
    ]
