# Generated by Django 5.1.2 on 2024-11-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0026_alter_product_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="tags",
        ),
        migrations.AddField(
            model_name="tag",
            name="product",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="tags",
                to="product_app.product",
                verbose_name="product",
            ),
        ),
    ]
