# Generated by Django 5.1.2 on 2024-11-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0027_remove_product_tags_tag_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="product",
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="products", to="product_app.tag"
            ),
        ),
    ]
