# Generated by Django 5.1.2 on 2024-11-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0028_remove_tag_product_product_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="product_app.tag"
            ),
        ),
    ]
