version: '3.8'
services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:4000"
    container_name: megano
    environment:
      - DOCKER_RUNTIME=1
#    volumes:
#      - media:/code/src/static/images
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
#    volumes:
#      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    expose:
      - 5432

  celery_worker:
    image: python_django_diploma-web
    command: celery -A python_django_diploma worker -l info
    depends_on:
      - web
      - redis

  redis:
    image: redis:alpine


# docker-compose down --rmi all
# docker-compose build
# docker-compose up