version: '3.8'
services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:5000"
    container_name: megano
    environment:
      - DOCKER_RUNTIME=True
    volumes:
      - media:/code/src/static/images
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    expose:
      - 5432

  celery_worker:
    image: python_django_diploma-web
    command: celery -A python_django_diploma worker -l info
    depends_on:
      - web
      - redis

  redis:
    image: redis:alpine


volumes:
  pgdata:
  media:


# docker-compose down --rmi all
# docker-compose build
# docker-compose up
# Список активных контейнеров
#docker ps
# Принудительная остановка всех контейнеров
# docker stop $(docker ps -aq)
# Удаление всех остановленных контейнеров
# docker rm $(docker ps -aq)

