version: '3.9'
services:
  web:
    build: .
    command: >
      bash -c "
        python manage.py migrate &&
        python manage.py loaddata fixtures/simple_data.json &&
        python manage.py runserver 0.0.0.0:5000
      "
    container_name: megano
    environment:
      - DOCKER_RUNTIME=1
    volumes:
      - media:/code/src/static/images
    ports:
      - "5000:5000"
    depends_on:
      - redis

  redis:
    image: redis:alpine

volumes:
  media:


