# Generated by Django 5.1.2 on 2024-10-14 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0002_remove_saleitem_price_remove_saleitem_title_and_more'),
        ('product_app', '0019_alter_productimage_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.product'),
        ),
    ]
