# Generated by Django 5.1.2 on 2024-10-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0004_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='title',
            field=models.CharField(default='Sale!!!', max_length=128),
        ),
    ]
