# Generated by Django 5.1.2 on 2024-10-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0005_sale_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='items',
        ),
        migrations.AddField(
            model_name='sale',
            name='items',
            field=models.ManyToManyField(null=True, to='catalog_app.saleitem'),
        ),
    ]
