# Generated by Django 5.1.2 on 2024-10-14 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0006_remove_sale_items_sale_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='items',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='catalog_app.sale'),
        ),
    ]
