# Generated by Django 5.1.2 on 2024-10-14 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0007_remove_sale_items_saleitem_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog_app.sale'),
        ),
    ]
