# Generated by Django 5.1.1 on 2024-09-17 09:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(null=True)),
                ('fullDescription', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('freeDelivery', models.BooleanField(default=True)),
                ('count', models.SmallIntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('rating', models.SmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.category')),
            ],
        ),
    ]
