# Generated by Django 5.1.2 on 2024-10-18 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basket_app", "0003_basket"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproduct",
            name="order",
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="basket",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="basket_app.basket",
            ),
        ),
    ]
