# Generated by Django 5.1.2 on 2024-10-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket_app', '0004_remove_orderproduct_order_orderproduct_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
