# Generated by Django 5.1.2 on 2024-10-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket_app', '0011_alter_orderproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
