# Generated by Django 5.1.2 on 2024-11-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basket_app", "0013_delete_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="totalCost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
