# Generated by Django 5.1.2 on 2024-11-28 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basket_app", "0015_order_guest_name_alter_order_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="guest_name",
            new_name="session_key",
        ),
    ]
